{"name": "Ошибка при создании пользователя с данными уже зарегистрированного пользователя ", "status": "passed", "start": 1718962722196, "stop": 1718962723135, "uuid": "d1f1f586-f79c-45f5-8d7b-aa095113e4c8", "historyId": "0d438a4d2f73fd339445316d7a909c3b", "testCaseId": "0d438a4d2f73fd339445316d7a909c3b", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_duplicate_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "11396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}