{"name": "Ошибка при создании пользователя с данными уже зарегистрированного пользователя ", "status": "passed", "start": 1718958680972, "stop": 1718958681970, "uuid": "9a38ae2c-b127-4002-b8fa-33054df36add", "historyId": "0d438a4d2f73fd339445316d7a909c3b", "testCaseId": "0d438a4d2f73fd339445316d7a909c3b", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_duplicate_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "3528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}