{"name": "Ошибка при создании пользователя с данными уже зарегистрированного пользователя ", "status": "passed", "start": 1718826679456, "stop": 1718826680274, "uuid": "bd59081d-43e1-49c5-b634-b88c4050c157", "historyId": "0d438a4d2f73fd339445316d7a909c3b", "testCaseId": "0d438a4d2f73fd339445316d7a909c3b", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_duplicate_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "17000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}